name: flutter_app
description: A Flutter application for recording and uploading audio

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.7.0
  firebase_storage: ^11.2.6
  permission_handler: ^11.0.0
  audioplayers: ^0.20.0
  cloud_firestore: ^4.9.1
  flutter_sound: ^9.2.13
  sqflite: ^2.3.0
  file_picker: ^5.5.0

environment:
  sdk: ">=2.12.0 <3.0.0"
